name: Lint, Build and Test Kami CLI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
jobs:
  lint-build-and-test:
    name: 'lint, build and test Kami CLI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Prettier
        run: pnpm prettier

      - name: Linting
        run: pnpm lint

      - name: Building
        run: pnpm build

      - name: Testing
        run: pnpm test